# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Moon' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Moon
  pod 'SFLiveKit', :git => 'https://github.com/Joygo-Technology/SFLiveKit-xh.git', :tag => '0.1.3'
  #pod 'SFLiveKit', :path => '../'
end
